config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/button'

  devise_for :users
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts, path: ''
  root 'posts#index'
  get 'bonus/digitalocean' => redirect('https://www.digitalocean.com/?refcode=5dcbfa133a56')

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :url, :content, presence: true
  validates :url, uniqueness: true
  extend FriendlyId
  friendly_id :url
  acts_as_taggable

  default_scope -> { order('created_at DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable
        # :recoverable, :rememberable, :registerable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Пожалуйста, сначала войди."
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 5)
    else
      @posts = Post.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Пост опубликован.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Пост обновлен.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Пост удален.' }
    end
  end

private
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :tag_list)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def button
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Фрей написал.'
    if page_title.empty?
      base_title
    else
      "#{page_title}, #{base_title}"
    end
  end

  def markdown(source)
    Kramdown::Document.new(source, coderay_line_numbers: nil).to_html.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
<hr>
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Frey, 2014-<%= Time.now.year %> </p>
            <% if current_user %>
              <%= link_to("Logout", destroy_user_session_path, :method => :delete) %>
            <% end %>
        </div>
    </div>
</footer>
</div>

<div class="counter">
  <!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter24265621 = new Ya.Metrika({id:24265621,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/24265621" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Frey', root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav pull-right">
                <li><%= link_to 'Обо мне', page_path('about') %></li>
                <% if current_user %>
                    <li><%= link_to 'Новая запись', new_post_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))  %></title>
  <%= stylesheet_link_tag font_awesome_css %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
     <%= yield %>
  </div>
</div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<img src="https://www.dropbox.com/s/g80ie1a310mlq31/_9_k7jHbLt0.jpg?dl=1" class="pull-left some-margins">
<p>Привет, меня зовут Евгений. С января 2013-го я занимаюсь Ruby, Rails и многими вещами, используемыми при работе с ними. Я очень люблю классные веб-приложения и постоянно пополняю багаж знаний (и практики) о том, как их делать, поддерживать и развивать. Так же мне интересен devops и получение опыта работы с высоконагруженными приложениями (распределение нагрузки, масштабирование).</p>
<p><a href="https://github.com/Freika"><%= icon :github, library: :font_awesome %> https://github.com/Freika</a></p>
<p><a href="https://twitter.com/forever_frey"><%= icon :twitter, library: :font_awesome %> https://twitter.com/forever_frey</a></p>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= f.label :title, "Название поста" %>
<br>
<%= f.text_field :title, class: "form-control" %>
<br>
<%= f.label :url, "Текст в URL" %>
<br>
<%= f.text_field :url, class: "form-control" %>
<br>
<%= f.text_area :content, class: "form-control insert-post-here", rows: 17 %>
<br>
<%= f.label :tag_list, "Список тегов" %>
<%= f.text_field :tag_list, class: 'form-control' %>
<br>
<%= f.submit "Опубликовать", class: "btn btn-success" %>

<% end %>

app/views/posts/edit.html.slim
h1
 | Редактирование записи
 = @post.title
= render 'form'
- provide(:title, "Редактируем #{@post.title}")

app/views/posts/index.html.slim
- @posts.each do |post|
  article.row
  aside.col-lg-2.post-meta
    span.publication-date= Russian::strftime(post.created_at, "%e %B %Y")
  .col-lg-10
    h2= link_to post.title, post
    - if post.tag_list.present?
      .tags
        | Темы:
        = raw post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ')
    - if current_user
        p= link_to 'Редактировать пост', edit_post_path(post)
        hr
    .post-content= markdown truncate(post.content, length: 500, separator: '\n')

= will_paginate @posts, previous_label: "← Туда", next_label: "Сюда →"

app/views/posts/new.html.slim
h1
  | Новая запись
= render 'form'
- provide(:title, "Пишем новый пост")

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
  <%= link_to 'Редактировать', edit_post_path(@post) %> |
  <%= link_to 'Удалить', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<article class="row">
  <aside class="col-lg-2 post-meta">
    <span class="publication-date"><%= Russian::strftime(@post.created_at, "%e %B %Y") %></span>
  </aside>

<div class="col-lg-10">
<!-- blog entry -->
     <h2><%= @post.title %></h2>
     <% if @post.tag_list.present? %>
       <div class="tags">
         Темы: <%= raw @post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %>
       </div>
     <% end %>
     <div class="post-content">
        <%= markdown @post.content %>
     </div>
</div>
<% provide(:title, @post.title) %>
</article>
<hr>

<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'frey-blog'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/static_pages/button.html.slim
h1 StaticPages#button
p Find me in app/views/static_pages/button.html.slim

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Редактируем профиль</h1>

<%= render 'form' %>

<%= link_to 'Показать', @user %> |
<%= link_to 'Назад', root_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>